baseurl = "https://surfacedfox.net"
title = " surfacedfox.net"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn slow" 


  [[params.navlinks]]
  name = " Projects/"
  url = "projects/"
  
  [[params.navlinks]]
  name = "󱀈 Posts/"
  url = "posts/"  
  

  [[params.navlinks]]
  name = " Contact/"
  url = "contact/"

  [[params.navlinks]]
  name = " GitHub/"
  url = "https://github.com/surfacedfox"
  
  [[params.navlinks]]
  name = "󰑫"
  url = "index.xml"

[[module.imports]]
path = "mermaid"